  
language: node_js
node_js:
  - node
script:
  - yarn web:build
  - yarn web:test

services:
  - docker

before_install:
  - docker build -t havana-web ./packages/havana-web/dist/ 

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 
