export const SET_REPORT_DATE = "SET_REPORT_DATE";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const SET_DIRECT_MANAGER = "SET_DIRECT_MANAGER";
export const SET_NOTIFICATIONS_COUNT = "SET_NOTIFICATIONS_COUNT";
export const DECREASE_NOTIFICATIONS_COUNT = "DECREASE_NOTIFICATIONS_COUNT";
export const INCREASE_NOTIFICATION_COUNT = "INCREASE_NOTIFICATION_COUNT";